version: "3.8"

services:
  app:
    container_name: exemplar_app
    build: .
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/app

  postgres:
    container_name: exemplar_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: exemplar_redis
    image: redis:7-alpine
    restart: always
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data

  redisinsight:
    container_name: exampler_redisinsight
    image: redislabs/redisinsight:latest
    volumes:
      - redisinsight:/db
    ports:
      - "8001:8001"

volumes:
  postgres:
  redis:
  redisinsight:
